### ISSUE TITLE
1.0.5 - invalid device error

### ISSUE THREAD

**Issue by Krongor** [wagesj45/butterflow-ui#4]
Windows 7
butterflow-ui 1.0.5

Process can't start when I'm trying to use my discrete GPU (GTX 1080ti). Issue doesn't occur on butterflow-ui 1.0.4.

**Comment by wagesj45** [comment]
Try opening opening the options dialog and setting your device manually.

*Edit* > *Application Options* > *Computing Device*

I had to add an option to force the CPU as the compute device because newer versions of the nVidia drivers break functionality with the CUDA/OpenCL libraries used in butterflow. Please let me know if this works. If it does, I have a pretty good idea of what the bug is and maybe I can fix it in a future release.

**Comment by Krongor** [comment]
Yes, it's the first thing I tried because I wanted to check how long it will take to process on CPU (Ryzen 7 2700 @3.9 Ghz). It works fine with -sw option in 1.0.5. 
Indeed, I'm aware about latest nVidia drivers issue, so I'm using version 399.07 to keep working with butterflow.
As for manual selecting Computing Device, I tried it and it shows "-device 1" line.

**Comment by wagesj45** [comment]
I didn't think to ask this earlier: If you copy the butterflow arguments and execute buterflow via the command line, do you still get the same issue? Would you be able to copy and paste the output from butterflow?

You can copy the command parameters by clicking *Edit* > *Copy butterflow arguments* or by clicking the *Copy* button in the lower left corner.

![image](https://user-images.githubusercontent.com/2460850/53220874-699f0180-362c-11e9-997f-3e9c6899e971.png)

The output messages from butterflow could be very helpful in locating the source of the bug.

**Comment by wagesj45** [comment]
@Krongor were you able to try copying out the butterflow arguments and get the butterflow output? If you have resolved the issue, I'll close the issue.
