### ISSUE TITLE
invalid device number

### ISSUE THREAD

**Issue by thescratcho** [wagesj45/butterflow-ui#5]
Windows 10 1903 
butterflow-ui 1.0.5
Amd Radeon Driver 19.6.1

if i try to use my gpu i get a error message

Heres a screenshot
![Unbenannt](https://user-images.githubusercontent.com/30008985/60079117-945dab80-972d-11e9-98f7-42499592508e.PNG)

**To Reproduce**
1. Go to Application Options
2. select gpu as computing device

**Comment by wagesj45** [comment]
Hey, sorry to hear about this. Would it be possible to copy the butterflow command (the button in the lower left hand corner of the application)? That will help me see what is actually getting sent to the butterflow application.

**Comment by thescratcho** [comment]
here you go

-v -vs 1920:1080 -device 1 -r 60 -audio -l -sm "randomvideo.mkv"

oh yeah i looked with butterflow itself what devices it detects, my gpu is listed as device 0
i used the butterflow 0.2.4alpha build to look at it

(are there any updates planed to your gui? maybe its useful to switch to build 0.2.4alpha)

**Comment by thescratcho** [comment]
![Unbenannt](https://user-images.githubusercontent.com/30008985/60100364-def51d00-9759-11e9-962a-5315437d6b43.PNG)

**Comment by wagesj45** [comment]
Thank you. Currently, I only have nVidia hardware in my machine, and there is a known issue with [butterflow right now that I'm hoping gets resolved at some point](https://github.com/dthpham/butterflow/issues/107). Until I can get a working copy of butterflow (alpha or otherwise) I'm afraid I won't be able to debug this locally.

### Work-Around

However, as a work-around, you can use the copy feature to run butterflow from the command line like you did here. I would remove the `-device 1`. Your command should look something like `butterflow.exe -v -vs 1920:1080 -r 60 -audio -l -sm "randomvideo.mkv"`

My guess is that the `Force CPU` option that I implemented as a workaround for the nVidia is causing you trouble. Maybe I indexed the compute devices wrong, but I can't tell for sure until I can debug locally, and that can't happen until we can build on Windows for nVidia hardware again.

I'll keep this issue open until we're able to build butterflow again and can fix the issue.
